color0   #141311
color1   #d65555
color2   #488c46
color3   #9c7855
color4   #7d8234
color5   #969686
color6   #c9c8ae
color7   #abb2bf
color8   #5c6370
color9   #e57e7e
color10   #416c40
color11   #735e4a
color12   #dddbb9
color13   #6c642b
color14   #616a35
color15   #ffffff

cursor #e5e2de
cursor_text_color #c9c6c2

foreground            #e5e2de
background            #141311
selection_foreground  #313125
selection_background  #c9c7b6
url_color             #c9c8ae