foreground              #FFFFFF
background              #161924
selection_foreground    #161924
selection_background    #FFFFFF
cursor                  #BD9169 
cursor_text_color       #111112

active_tab_foreground     #161924
active_tab_background     #665143
inactive_tab_foreground   #665143
inactive_tab_background   #161924

# black
color0      #293252
color8      #57638F

# red
color1      #FFE4CC
color9      #F0CBAA

# green
color2      #FFCCEB
color10     #F0AAD4

# yellow
color3      #FFE0CC
color11     #F0C6AA

# blue
color4      #9AAAE6
color12     #9AAAE6

# magenta
color5      #E69AC7
color13     #E69AC7

# cyan
color6      #E6B89A
color14     #E6B89A

# white
color7      #FFE4CC
color15     #F0CBAA
