#!/bin/sh
# sb-cpu — CPU usage with delta calculation

read cpu a b c previdle rest < /proc/stat
prevtotal=$((a+b+c+previdle))
sleep 0.25
read cpu a b c idle rest < /proc/stat
total=$((a+b+c+idle))

cpu=$((200 * ( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal+1) ))
cpu=$((cpu / 2))

printf "󰻠 %s%%" "$cpu"
